Repository TeeWhyKay/Chomp, pull requests merged in 2021-10, with the labels that each got.

#132 implemented budget slider + fix time/date bug
  app/assets/stylesheets/components/_form.scss
  app/javascript/controllers/selecting_cuisines_controller.js
  app/models/chomp_session.rb
  app/views/responses/_form.html.erb
Labels: bug, enhancement, aesthetics

#137 fix redirection routes
  app/controllers/chomp_sessions_controller.rb
  app/views/chomp_sessions/success.html.erb
Labels: hotfix

#136 Change fav position
  app/assets/stylesheets/pages/_restaurant_show.scss
  app/views/restaurants/show.html.erb
Labels: aesthetics

#128 seeding more images for each restaurant
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/_carousel.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/pages/_restaurant_show.scss
  app/models/restaurant.rb
  app/views/pages/favorites.html.erb
  app/views/restaurants/_carousel.html.erb
  app/views/restaurants/show.html.erb
  db/seeds.rb
Labels: enhancement, seeding needed

#138 moved lower
  app/assets/stylesheets/pages/_restaurant_show.scss
Labels: hotfix

#139 location pin is aligned
  app/assets/stylesheets/components/_search_form.scss
Labels: hotfix, aesthetics

#140 Fixed share button after input preferences
  app/views/responses/show.html.erb
Labels: bugfix

#141 quickfix for dashboard
  app/views/chomp_sessions/_my_sessions_table.html.erb
Labels: hotfix

#142 fixed website not working for non-http
  app/views/restaurants/show.html.erb
Labels: hotfix

#143 remove border on img
  app/views/restaurants/_carousel.html.erb
Labels: hotfix

#144 Centralised landing page form on mobile
  app/assets/stylesheets/pages/_home.scss
Labels: bugfix, aesthetics

#145 filter out responses that sessions are alr expired
  app/controllers/chomp_sessions_controller.rb
Labels: hotfix

#146 force serve https for rails app
  config/environments/production.rb
Labels: production config

#151 first draft of readme
  readme.md
Labels: readme

#152 Make review easier
  app/javascript/controllers/insert_in_list_controller.js
  app/models/review.rb
  app/views/restaurants/_review.html.erb
  app/views/restaurants/show.html.erb
  app/views/reviews/_appended_review.html.erb
  app/views/reviews/_edit_review_form.html.erb
  app/views/reviews/_form.html.erb
  db/migrate/20211004105053_remove_title_from_reviews.rb
  db/schema.rb
Labels: enhancement, migration needed
