Repository TeeWhyKay/Chomp, pull requests merged in 2021-09, with the labels that each got.

#3 new gemlock
  Gemfile.lock
Labels: bug

#7 Devops on Heroku: Procfile for auto migrations each release
  Procfile
Labels: devops

#8 Responses model
  app/models/response.rb
  db/migrate/20210921102717_create_responses.rb
  db/schema.rb
  test/models/response_test.rb
Labels: enhancement, migration needed

#9 Feature/add reviews to restaurants
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_show.scss
  app/controllers/restaurants_controller.rb
  app/controllers/reviews_controller.rb
  app/javascript/controllers/hello_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/insert_in_list_controller.js
  app/javascript/packs/application.js
  app/views/restaurants/_review.html.erb
  app/views/restaurants/index.html.erb
  app/views/restaurants/show.html.erb
  app/views/reviews/_appended_review.html.erb
  app/views/reviews/_form.html.erb
  app/views/reviews/create.json.jbuilder
  config/application.rb
  config/routes.rb
  db/migrate/20210921131813_add_photo_url_to_restaurants.rb
  db/migrate/20210921140538_add_average_rating_to_restaurants.rb
  db/schema.rb
  package.json
  test/controllers/restaurants_controller_test.rb
  test/controllers/reviews_controller_test.rb
  yarn.lock
Labels: enhancement, migration needed, seeding needed

#17 Seed some restaurants
  .gitignore
  Gemfile
  Gemfile.lock
  app/models/restaurant.rb
  app/views/pages/home.html.erb
  config/environments/development.rb
  config/storage.yml
  db/migrate/20210922072018_create_active_storage_tables.active_storage.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement, migration needed, seeding needed

#16 Seed for session
  db/seeds.rb
Labels: seeding needed

#18 Added favicon and logo to navbar
  app/assets/images/default-monochrome-black.svg
  app/assets/images/logo-only.svg
  app/views/layouts/application.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#19 chomp session creation successful
  app/controllers/chomp_sessions_controller.rb
  app/models/chomp_session.rb
  app/views/chomp_sessions/new.html.erb
  app/views/chomp_sessions/success.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20210922084032_separate_time_and_date.rb
  db/schema.rb
Labels: migration needed

#22 seeding restaurants with price and from 12 cuisines
  db/migrate/20210923042717_add_google_rating_to_restaurants.rb
  db/migrate/20210923042950_add_pricing_to_restaurants.rb
  db/schema.rb
  db/seeds.rb
Labels: migration needed, seeding needed

#26 Feat geocoding restaurant
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  app/javascript/plugins/init_location.js
  app/models/response.rb
  app/models/restaurant.rb
  config/initializers/geocoder.rb
  db/seeds.rb
Labels: enhancement, seeding needed, bundle install needed

#27 Feature/email results of chomp session
  .env.sample
  Gemfile
  Gemfile.lock
  app/controllers/chomp_sessions_controller.rb
  app/mailers/application_mailer.rb
  app/mailers/chomp_session_mailer.rb
  app/mailers/user_mailer.rb
  app/models/chomp_session.rb
  app/models/user.rb
  app/views/chomp_session_mailer/create_chomp.html.erb
  app/views/chomp_session_mailer/create_chomp.text.erb
  app/views/chomp_session_mailer/create_confirmation.html.erb
  app/views/chomp_session_mailer/create_confirmation.text.erb
  app/views/pages/home.html.erb
  app/views/user_mailer/welcome.html.erb
  app/views/user_mailer/welcome.text.erb
  config/credentials.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/smtp.rb
  db/schema.rb
  test/mailers/chomp_session_mailer_test.rb
  test/mailers/previews/chomp_session_mailer_preview.rb
  test/mailers/previews/user_mailer_preview.rb
  test/mailers/user_mailer_test.rb
Labels: enhancement, bundle install needed

#39 changed settings to run cloudinary on production
  config/environments/production.rb
Labels: production config

#38 Upgrade email sending to sidekiq
  app/controllers/chomp_sessions_controller.rb
  app/models/chomp_session.rb
  app/views/chomp_session_mailer/create_chomp.html.erb
  app/views/chomp_session_mailer/create_chomp.text.erb
  app/views/chomp_session_mailer/update_chomp.html.erb
  app/views/chomp_session_mailer/update_chomp.text.erb
Labels: hotfix

#40 Logo fix in production
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
  db/schema.rb
Labels: urgent production fix

#37 Feat get user location
  app/assets/stylesheets/pages/_form.scss
  app/assets/stylesheets/pages/_index.scss
  app/controllers/responses_controller.rb
  app/javascript/plugins/init_location.js
  app/models/response.rb
  app/views/responses/new.html.erb
  config/initializers/geocoder.rb
  config/routes.rb
  db/migrate/20210923141452_rename_location_to_address_for_responses.rb
Labels: enhancement, migration needed, bundle install needed

#42 updated response form partial
  app/views/responses/_form.html.erb
Labels: hotfix

#44 Feat close poll, generate results, edit seeding method
  app/controllers/chomp_sessions_controller.rb
  app/views/responses/show.html.erb
  app/views/restaurants/show.html.erb
  config/routes.rb
  db/seeds.rb
Labels: enhancement, migration needed, seeding needed, bugfix

#46 heroku redis setup
  Procfile
  config/initializers/redis.rb
  db/schema.rb
Labels: production config

#53 Update email to show chomp sess link
  app/mailers/chomp_session_mailer.rb
  app/mailers/response_mailer.rb
  app/views/chomp_session_mailer/create_chomp.html.erb
  app/views/chomp_session_mailer/create_chomp.text.erb
  app/views/chomp_session_mailer/update_chomp.html.erb
  app/views/chomp_session_mailer/update_chomp.text.erb
  app/views/response_mailer/create_response.html.erb
  app/views/response_mailer/create_response.text.erb
  app/views/response_mailer/update_response.html.erb
  app/views/response_mailer/update_response.text.erb
Labels: enhancement

#54 Add animate style
  app/javascript/packs/application.js
  app/views/chomp_sessions/success.html.erb
  app/views/responses/show.html.erb
  package.json
  yarn.lock
Labels: enhancement, yarn install

#64 Response input now has default value for lazy people
  app/controllers/responses_controller.rb
  app/views/responses/_form.html.erb
  app/views/responses/new.html.erb
  config/environments/development.rb
Labels: enhancement, bugfix

#63 deliver_now to _later
  app/models/user.rb
Labels: hotfix

#70 Map function
  app/javascript/packs/application.js
  app/views/layouts/application.html.erb
  app/views/restaurants/_map.html.erb
  app/views/restaurants/show.html.erb
  package.json
  yarn.lock
Labels: enhancement

#69 Feature/send restaurant result email
  app/controllers/chomp_sessions_controller.rb
  app/mailers/restaurant_result_mailer.rb
  app/views/restaurant_result_mailer/result_release.html.erb
  app/views/restaurant_result_mailer/result_release.text.erb
  test/mailers/previews/restaurant_result_mailer_preview.rb
  test/mailers/restaurant_result_mailer_test.rb
Labels: enhancement

#67 Seed restaurant website
  db/migrate/20210926064931_add_website_url_to_restaurants.rb
  db/schema.rb
  db/seeds.rb
Labels: migration needed, seeding needed

#68 warning modal implemented
  Gemfile.lock
  app/controllers/chomp_sessions_controller.rb
  app/views/responses/_generatemodal.html.erb
  app/views/responses/show.html.erb
Labels: enhancement

#71 Feature: generating restaurant result from responses
  Gemfile
  Gemfile.lock
  app/controllers/chomp_sessions_controller.rb
  app/models/chomp_session.rb
  app/models/restaurant.rb
  db/migrate/20210926101731_add_description_to_restaurant.rb
  db/migrate/20210926103907_add_body_to_restaurants.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement, migration needed, bundle install needed

#76 added missing end, removed unused dependencies
  Gemfile.lock
  app/controllers/chomp_sessions_controller.rb
  db/schema.rb
Labels: bugfix

#74 See number of responses for the ChompSession
  app/models/chomp_session.rb
  app/views/responses/show.html.erb
Labels: enhancement, migration needed

#83 fixing fonts on production
  app/assets/stylesheets/application.scss
Labels: urgent production fix, bugfix

#79 my-dashboard complete + expandable map
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/pages/_dashboard.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_restaurant_show.scss
  app/controllers/chomp_sessions_controller.rb
  app/views/chomp_sessions/_my_responses_table.html.erb
  app/views/chomp_sessions/_my_sessions_table.html.erb
  app/views/chomp_sessions/dashboard.html.erb
  app/views/responses/show.html.erb
  app/views/restaurants/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  dump.rdb
Labels: enhancement

#72 Add bg to landing
  app/assets/stylesheets/components/_search_form.scss
  app/assets/stylesheets/config/_fonts.scss
  app/assets/stylesheets/pages/_all_pages.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_index.scss
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
Labels: aesthetics

#81 Feat generate results on expiry
  app/controllers/chomp_sessions_controller.rb
  app/jobs/chompsession_cancellation_job.rb
  app/jobs/generate_restaurant_job.rb
  db/migrate/20210927072812_add_sidekiq_jid_to_chomp_sessions.rb
  db/schema.rb
  test/jobs/chompsession_cancellation_job_test.rb
  test/jobs/generate_restaurant_job_test.rb
Labels: enhancement, migration needed

#80 Feat review count update realtime
  app/javascript/controllers/insert_in_list_controller.js
  app/views/restaurants/_review.html.erb
  app/views/restaurants/show.html.erb
  app/views/reviews/_edit_review_form.html.erb
  app/views/reviews/_form.html.erb
Labels: enhancement

#85 added slash in front of pages
  app/views/layouts/application.html.erb
Labels: hotfix

#82 Add favourite icon in restaurant image
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/pages/_restaurant_show.scss
  app/controllers/restaurants_controller.rb
  app/javascript/packs/application.js
  app/models/favorite.rb
  app/models/restaurant.rb
  app/models/user.rb
  app/views/restaurants/index.html.erb
  app/views/restaurants/show.html.erb
  config/initializers/acts_as_favoritor.rb
  config/routes.rb
  db/migrate/20210927024317_acts_as_favoritor_migration.rb
  db/schema.rb
Labels: migration needed, bundle install needed

#88 Review edit button doesn't show if not written by current user
  app/views/restaurants/_review.html.erb
  app/views/reviews/_appended_review.html.erb
Labels: hotfix

#90 Attempting to fix production fonts on heroku
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/config/_fonts.scss
Labels: bugfix

#91 added notice message to users
  app/views/chomp_sessions/_email_notification_notice.html.erb
  app/views/chomp_sessions/edit.html.erb
  app/views/chomp_sessions/show.html.erb
  app/views/responses/edit.html.erb
Labels: enhancement

#92 updated default chomp sess names
  app/controllers/chomp_sessions_controller.rb
  app/views/chomp_sessions/_form.html.erb
Labels: enhancement

#93 UPDATE: Fix Sign Up issue + simple time reminder implemented
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_timer.scss
  app/javascript/packs/application.js
  app/models/user.rb
  app/views/chomp_sessions/_timer.html.erb
  app/views/chomp_sessions/show.html.erb
  app/views/devise/registrations/new.html.erb
  dump.rdb
Labels: enhancement, hotfix

#96 fixing all forms with unecessary remote:true
  app/views/chomp_sessions/_form.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/responses/_form.html.erb
Labels: bugfix

#97 changed h2 to h1
  app/views/chomp_sessions/edit.html.erb
  app/views/chomp_sessions/new.html.erb
Labels: aesthetics

#95 fix chomp link
  app/views/chomp_sessions/_my_sessions_table.html.erb
  app/views/chomp_sessions/dashboard.html.erb
  app/views/responses/show.html.erb
Labels: hotfix

#94 Update navbar transparent
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/shared/_navbar.html.erb
Labels: enhancement, aesthetics

#98 fixed edit user session alignment issue #57
  app/assets/stylesheets/components/_tab.scss
  app/views/devise/registrations/edit.html.erb
Labels: bugfix

#100 Update/chomp font passion
  app/assets/fonts/lovelo-black-webfont.woff
  app/assets/fonts/lovelo-black-webfont.woff2
  app/assets/fonts/lovelo-linebold-webfont.woff
  app/assets/fonts/lovelo-linebold-webfont.woff2
  app/assets/fonts/lovelo-linelight-webfont.woff
  app/assets/fonts/lovelo-linelight-webfont.woff2
  app/assets/stylesheets/components/_meetup_details.scss
  app/assets/stylesheets/components/_timer.scss
  app/assets/stylesheets/config/_fonts.scss
  app/assets/stylesheets/pages/_responses.scss
Labels: aesthetics

#104 Update/chomp logo
  app/assets/stylesheets/pages/_home.scss
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
Labels: aesthetics

#102 Feature/google sign in
  .env.sample
  Gemfile
  Gemfile.lock
  app/controllers/omniauth_callbacks_controller.rb
  app/models/chomp_session.rb
  app/models/user.rb
  app/views/devise/shared/_links.html.erb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20210928080921_add_columns_to_users.rb
  db/schema.rb
Labels: enhancement

#108 missing comma breaking staging build
  app/models/user.rb
Labels: hotfix

#106 Invitees-limit function implemented + validation added on form for session-expiry
  app/controllers/chomp_sessions_controller.rb
  app/controllers/responses_controller.rb
  app/jobs/generate_restaurant_job.rb
  app/models/chomp_session.rb
  app/views/chomp_sessions/_form.html.erb
  app/views/restaurants/show.html.erb
  config/routes.rb
  db/migrate/20210929042213_add_user_limit_to_session.rb
  db/schema.rb
  dump.rdb
Labels: enhancement, migration needed

#109 Fix/chomp sess link not working
  app/views/chomp_sessions/success.html.erb
  app/views/responses/show.html.erb
Labels: bugfix

#99 List of user favourites
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/favorites.scss
  app/controllers/pages_controller.rb
  app/views/pages/favorites.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20210928071301_acts_as_favoritor_migration.rb
Labels: enhancement

#110 fix chomp_session to be within validation
  db/seeds.rb
Labels: seeding needed, hotfix

#107 navbar show email on mobile view
  app/views/shared/_navbar.html.erb
Labels: aesthetics

#118 remove dotcss
  app/javascript/packs/application.js
Labels: bugfix

#119 Implemented new plus minus icons to adjust number of friends
  app/assets/stylesheets/components/_form.scss
  app/models/chomp_session.rb
  app/views/chomp_sessions/_form.html.erb
Labels: enhancement

#113 Remove/excessive emails
  app/controllers/chomp_sessions_controller.rb
  app/controllers/responses_controller.rb
  app/mailers/chomp_session_mailer.rb
  app/mailers/response_mailer.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/chomp_session_mailer/create_chomp.html.erb
  app/views/chomp_session_mailer/create_chomp.text.erb
  app/views/chomp_session_mailer/update_chomp.html.erb
  app/views/chomp_session_mailer/update_chomp.text.erb
  app/views/chomp_sessions/_email_notification_notice.html.erb
  app/views/response_mailer/create_response.html.erb
  app/views/response_mailer/create_response.text.erb
  app/views/response_mailer/update_response.html.erb
  app/views/response_mailer/update_response.text.erb
  app/views/user_mailer/welcome.html.erb
  app/views/user_mailer/welcome.text.erb
  test/mailers/chomp_session_mailer_test.rb
  test/mailers/previews/chomp_session_mailer_preview.rb
  test/mailers/previews/response_mailer_preview.rb
  test/mailers/previews/user_mailer_preview.rb
  test/mailers/response_mailer_test.rb
  test/mailers/user_mailer_test.rb
Labels: enhancement

#125 Changing email service to mailgun using mailgun gem
  Gemfile
  Gemfile.lock
  app/mailers/application_mailer.rb
  app/mailers/restaurant_result_mailer.rb
  config/environments/development.rb
  config/environments/production.rb
Labels: enhancement, bundle install needed

#115 Hotfix/wording choice
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/assets/stylesheets/config/_fonts.scss
  app/assets/stylesheets/pages/_restaurant_show.scss
  app/views/chomp_sessions/_form.html.erb
  app/views/chomp_sessions/_my_sessions_table.html.erb
  app/views/chomp_sessions/dashboard.html.erb
  app/views/chomp_sessions/success.html.erb
  app/views/pages/favorites.html.erb
  app/views/pages/home.html.erb
  app/views/responses/_form.html.erb
  app/views/responses/show.html.erb
  app/views/restaurants/_review.html.erb
  app/views/restaurants/show.html.erb
  app/views/shared/_navbar.html.erb
Labels: hotfix

#120 Feature/select all text in loc on click
  app/views/chomp_sessions/_form.html.erb
  app/views/responses/_form.html.erb
Labels: enhancement

#126 added condition to not show notice if user login
  app/views/responses/show.html.erb
Labels: hotfix

#123 Sticky timer + change button size
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_timer.scss
  app/views/chomp_sessions/_form.html.erb
  app/views/chomp_sessions/_timer.html.erb
  app/views/chomp_sessions/show.html.erb
Labels: aesthetics

#121 Share link button now works on both mobile (chrome) and desktop
  app/javascript/packs/application.js
  app/javascript/plugins/init_share_button.js
  app/views/chomp_sessions/success.html.erb
  app/views/responses/show.html.erb
Labels: enhancement

#129 Fix/navbar positioning not consistent
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/shared/_navbar.html.erb
Labels: aesthetics

#124 Feature/autofill time based on chomp name
  app/javascript/controllers/chomp_controller.js
  app/views/chomp_sessions/_form.html.erb
Labels: enhancement

#130 rounded increment btn
  app/assets/stylesheets/components/_form.scss
  app/views/chomp_sessions/_form.html.erb
Labels: aesthetics

#127 UI/move submit pref btn higher
  app/views/chomp_sessions/_my_sessions_table.html.erb
  app/views/chomp_sessions/success.html.erb
  app/views/responses/show.html.erb
  app/views/reviews/_edit_review_form.html.erb
  app/views/reviews/_form.html.erb
Labels: aesthetics

#135 added containers etc to new responses pg
  app/controllers/responses_controller.rb
  app/views/responses/new.html.erb
Labels: hotfix, aesthetics
